services:
    question_factory:
        class: DictionaryBundle\Entity\QuestionFactory

    dictionary_mapper_factory:
        class: DictionaryBundle\Mapper\DictionaryMapperFactory

    dictionary_array_mapper:
        class: DictionaryBundle\Mapper\DictionaryArray
        factory: ['@dictionary_mapper_factory', createDictionaryMapper]
        arguments: ['%kernel.root_dir%', '%dictionary_source_path%']

    examination_service_factory:
        class: DictionaryBundle\Service\ExaminationServiceFactory

    examination:
        class: DictionaryBundle\Service\ExaminationService
        factory: ['@examination_service_factory', createSerivce]
        arguments:
            - '%questions_count%'
            - '@request_stack'
            - '@dictionary_array_mapper'
            - '@question_factory'
